# Generated by Django 6.0.3 on 2026-03-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField()),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='study_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='study_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='study_images/')),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StudyEntry',
        ),
    ]
