# Generated by Django 6.0.3 on 2026-03-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_tracker_delete_studyentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tracker',
            new_name='StudyEntry',
        ),
    ]
