# Generated by Django 6.0.3 on 2026-03-14 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_studyentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studyentry',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='studyentry',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='studyentry',
            name='image3',
        ),
        migrations.AlterField(
            model_name='studyentry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studyentry',
            name='progress',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='StudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='study_images/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tracker.studyentry')),
            ],
        ),
    ]
