# Generated by Django 6.0.3 on 2026-03-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_studyentry_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyentry',
            name='drawing',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/'),
        ),
        migrations.AddField(
            model_name='studyentry',
            name='drawing_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
