# Generated by Django 6.0.3 on 2026-03-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_studyentry_drawing_studyentry_drawing_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyentry',
            name='drawing',
        ),
        migrations.RemoveField(
            model_name='studyentry',
            name='drawing_json',
        ),
    ]
