# Generated by Django 6.0.3 on 2026-03-15 07:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_studyentry_drawing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyentry',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studyentry',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
