# Generated by Django 6.0.3 on 2026-03-26 10:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_studyentry_description_alter_studyentry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyentry',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='studyentry',
            name='notes',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
