# Generated by Django 6.0.3 on 2026-03-26 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_studyentry_description_alter_studyentry_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
