# Generated by Django 6.0.3 on 2026-03-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_studyentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
